name: Bug Report
description: 报告一个问题，帮助我们定位并修复
title: "[Bug] "
labels:
  - bug
body:
  - type: input
    id: bt_version
    attributes:
      label: BT 版本
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: 复现步骤
      description: 如果是播放器相关的问题（例如卡顿、画质异常、播放错误等），请在开发者模式打开“播放流程日志”，用手机或电脑访问日志第一行显示的地址，然后把日志内容贴到这里。
    validations:
      required: true
